// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGRMbby5LmtvgoO4YkFw6DKCC03Lx3Co',
    appId: '1:785256724411:web:9741752724162c89cbb69e',
    messagingSenderId: '785256724411',
    projectId: 'kawiarnia-2919a',
    authDomain: 'kawiarnia-2919a.firebaseapp.com',
    storageBucket: 'kawiarnia-2919a.firebasestorage.app',
    measurementId: 'G-XT197NYE0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-yeCzbVz8OtgZhEfuaeI0BkcJuphLlA',
    appId: '1:785256724411:android:f836990d71732bf1cbb69e',
    messagingSenderId: '785256724411',
    projectId: 'kawiarnia-2919a',
    storageBucket: 'kawiarnia-2919a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ej8cBkGDzDHEMg5Cp3AhZXAx8B25vHM',
    appId: '1:785256724411:ios:827658202e5cbf5bcbb69e',
    messagingSenderId: '785256724411',
    projectId: 'kawiarnia-2919a',
    storageBucket: 'kawiarnia-2919a.firebasestorage.app',
    iosBundleId: 'com.example.kawiarnia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ej8cBkGDzDHEMg5Cp3AhZXAx8B25vHM',
    appId: '1:785256724411:ios:827658202e5cbf5bcbb69e',
    messagingSenderId: '785256724411',
    projectId: 'kawiarnia-2919a',
    storageBucket: 'kawiarnia-2919a.firebasestorage.app',
    iosBundleId: 'com.example.kawiarnia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcGRMbby5LmtvgoO4YkFw6DKCC03Lx3Co',
    appId: '1:785256724411:web:cec17c586becc102cbb69e',
    messagingSenderId: '785256724411',
    projectId: 'kawiarnia-2919a',
    authDomain: 'kawiarnia-2919a.firebaseapp.com',
    storageBucket: 'kawiarnia-2919a.firebasestorage.app',
    measurementId: 'G-J1KE8QDFYM',
  );
}
